const mockExercises = [
  {
    id: 3,
    name: "Диагонали",
    description:
      "Попеременно нужно переводить взгляд по диагонали. Для этого хорошо подходит окно.",
    isDone: true,
    duration: 85,
    steps: [
      {
        title: "",
        description: "Начинаем...",
        duration: 3,
        sleepAfter: 0,
      },
      {
        image: "diagonals.jpg",
        title: "",
        description: "Переведите взгляд по диагонали слева направо",
        duration: 5,
        sleepAfter: 0,
        audio: "diagonals-1.mp3",
      },
      {
        image: "diagonals.jpg",
        title: "",
        description: "Переведите взгляд по диагонали справа налево",
        duration: 5,
        sleepAfter: 0,
        audio: "diagonals-2.mp3",
      },
      {
        image: "diagonals.jpg",
        title: "",
        description: "Повторите это 7-10 раз",
        duration: 0,
        sleepAfter: 0,
        audio: "diagonals-3.mp3",
      },
      {
        image: "blinking.jpg",
        title: "",
        description: "А теперь быстро начните моргать в течение 15 секунд",
        duration: 15,
        sleepAfter: 0,
        audio: "diagonals-4.mp3",
      },
    ],
  },
  {
    id: 1,
    name: "Моргание",
    description: "Моргать нужно быстро, не напрягая глаз в течение полминуты.",
    isDone: true,
    duration: 40,
    steps: [
      {
        title: "",
        description: "Готовы?",
        duration: 3,
        sleepAfter: 0,
      },
      {
        image: "blinking.png",
        title: "",
        description: "Необходимо быстро моргать в течение полуминуты",
        duration: 30,
        sleepAfter: 10,
        audio: "blinking-1.mp3",
      },
    ],
  },
  {
    id: 2,
    name: "Стрелки",
    description:
      "Глазами нужно водить поочередно вправо и влево, в течение одной минуты, потом поморгать 10 секунд.",
    isDone: true,
    duration: 70,
    steps: [
      {
        title: "",
        description: "Приготовьтесь.",
        duration: 3,
        sleepAfter: 0,
      },
      {
        image: "arrows.jpg",
        title: "",
        description:
          "Глазами нужно водить поочередно вправо и влево в течение полуминуты",
        duration: 30,
        sleepAfter: 0,
        audio: "arrows-1.mp3",
      },
      {
        image: "blinking.jpg",
        title: "",
        description: "А теперь необходимо быстро поморгать в течение 10 сек",
        duration: 10,
        sleepAfter: 20,
        audio: "arrows-2.mp3",
      },
    ],
  },
  {
    id: 4,
    name: "Вертикаль",
    description:
      "Как понятно из названия, движения глаз направлены вверх и вниз.",
    isDone: true,
    duration: 75,
    steps: [
      {
        title: "",
        description: "Готовы?",
        duration: 3,
        sleepAfter: 0,
      },
      {
        image: "vertical.jpg",
        title: "",
        description: "Поочерёдно водите глазами вверх и вниз 7-10 раз",
        duration: 0,
        sleepAfter: 0,
        audio: "vertical-1.mp3",
      },
      {
        image: "blinking.jpg",
        title: "",
        description: "А теперь быстро начните моргать в течение 15 сек",
        duration: 15,
        sleepAfter: 0,
        audio: "vertical-2.mp3",
      },
    ],
  },
  {
    id: 5,
    name: "Прямоугольник",
    description:
      "Нужно нарисовать в воздухе воображаемый квадрат или прямоугольник.",
    isDone: true,
    duration: 75,
    steps: [
      {
        title: "",
        description: "Скоро начнём!",
        duration: 3,
        sleepAfter: 0,
      },
      {
        image: "rectangle.jpg",
        title: "",
        description:
          "Нарисуйте в воздухе воображаемый прямоугольник, начиная с левого нижнего угла",
        duration: 5,
        sleepAfter: 0,
        audio: "rectangle-1.mp3",
      },
      {
        image: "rectangle.jpg",
        title: "",
        description: "Стерите прямоугольник, идя в обратную сторону",
        duration: 5,
        sleepAfter: 0,
        audio: "rectangle-2.mp3",
      },
      {
        image: "rectangle.jpg",
        title: "",
        description: "Повторите это 3 раза",
        duration: 0,
        sleepAfter: 0,
        audio: "rectangle-3.mp3",
      },
      {
        image: "blinking.jpg",
        title: "",
        description: "А теперь быстро поморгайте в течение 15 сек",
        duration: 15,
        sleepAfter: 0,
        audio: "rectangle-4.mp3",
      },
    ],
  },
  {
    id: 6,
    name: "Зигзаги",
    description: "Нужно нарисовать в воздухе воображаемый зигзаг.",
    isDone: true,
    duration: 75,
    steps: [
      {
        title: "",
        description: "Готовьтесь.",
        duration: 3,
        sleepAfter: 0,
      },
      {
        image: "zigzags.jpg",
        title: "",
        description: "Нарисуйте в воздухе воображаемый зигзаг",
        duration: 7,
        sleepAfter: 0,
        audio: "zigzags-1.mp3",
      },
      {
        image: "zigzags.jpg",
        title: "",
        description: "Повторите это 5 раз",
        duration: 0,
        sleepAfter: 0,
        audio: "zigzags-2.mp3",
      },
      {
        image: "blinking.jpg",
        title: "",
        description: "А теперь быстро поморгайте в течение 15 сек",
        duration: 15,
        sleepAfter: 0,
        audio: "zigzags-3.mp3",
      },
    ],
  },
  {
    id: 7,
    name: "Цифры",
    description:
      "Во время этого упражнения глазами двигают как часовой стрелкой, останавливая свой взгляд на 3, 6, 9 и 12 часах.",
    isDone: true,
    duration: 75,
    steps: [
      {
        title: "",
        description: "Уже начинаем!",
        duration: 3,
        sleepAfter: 0,
      },
      {
        image: "numbers.jpg",
        title: "",
        description:
          "Двигайте глазами по часовой стрелке, останавливая свой взгляд на 3, 6, 9 и 12 часах",
        duration: 7,
        sleepAfter: 0,
        audio: "numbers-1.mp3",
      },
      {
        image: "numbers.jpg",
        title: "",
        description: "Повторите это 2 раза по часовой стрелке",
        duration: 0,
        sleepAfter: 0,
        audio: "numbers-2.mp3",
      },
      {
        image: "numbers.jpg",
        title: "",
        description: "А затем 2 раза против часовой стрелки",
        duration: 0,
        sleepAfter: 0,
        audio: "numbers-3.mp3",
      },
      {
        image: "blinking.jpg",
        title: "",
        description: "Быстро моргайте",
        duration: 15,
        sleepAfter: 0,
        audio: "numbers-4.mp3",
      },
    ],
  },
];

export default mockExercises;